/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ActniSir;

/**
 *
 * @author cieloalynahfaereyes
 */
public class MConv extends javax.swing.JFrame {

    /**
     * Creates new form MConv
     */
    public MConv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("To");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Result");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Philippine Peso", "US Dollar", "Euro", "British Pound", "Indian Rupee", "Australian Dollar", "Canadian Dollar", "Singapore Dollar", "Swiss Franc", "Malaysian Ringgit", "Japanese Yen" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Philippine Peso", "US Dollar", "Euro", "British Pound", "Indian Rupee", "Australian Dollar", "Canadian Dollar", "Singapore Dollar", "Swiss Franc", "Malaysian Ringgit", "Japanese Yen" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)))
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String box1= (String)jComboBox1.getSelectedItem();
        String box2= (String)jComboBox2.getSelectedItem();

        if(box1.equals("Philippine Peso")&& box2.equals("US Dollar")){
            double ph=Double.parseDouble(jTextField1.getText());
            double us=(double)(ph*58.01000);
            jTextField4.setText(String.valueOf(us));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Euro")) {
            double ph=Double.parseDouble(jTextField1.getText());
            double eu=(double)(ph*90.93);
            jTextField4.setText(String.valueOf(eu));
        } else if (box1.equals("Philippine Peso")&&box2.equals("British Pound")){
            double ph=Double.parseDouble(jTextField1.getText());
            double bp=(double)(ph*90.94);
            jTextField4.setText(String.valueOf(bp));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Indian Rupee")) {
            double ph=Double.parseDouble(jTextField1.getText());
            double ir=(double)(ph*1.00);
            jTextField4.setText(String.valueOf(ir));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Australian Dollar")){
            double ph=Double.parseDouble(jTextField1.getText());
            double ad=(double)(ph*55.09);
            jTextField4.setText(String.valueOf(ad));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Canadian Dollar")) {
            double ph=Double.parseDouble(jTextField1.getText());
            double cd=(double)(ph*0.025);
            jTextField4.setText(String.valueOf(cd));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Singapore Dollar")){
            double ph=Double.parseDouble(jTextField1.getText());
            double sd=(double)(ph*0.024);
            jTextField4.setText(String.valueOf(sd));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Swiss Franc")) {
            double ph=Double.parseDouble(jTextField1.getText());
            double sf=(double)(ph*0.016);
            jTextField4.setText(String.valueOf(sf));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Malaysian Ringgit")){
            double ph=Double.parseDouble(jTextField1.getText());
            double mr=(double)(ph*0.0763);
            jTextField4.setText(String.valueOf(mr));
        } else if (box1.equals("Philippine Peso")&&box2.equals("Japanese Yen")){
            double ph=Double.parseDouble(jTextField1.getText());
            double jy=(double)(ph*2.61);
            jTextField4.setText(String.valueOf(jy));
        }
        
        if(box1.equals("US Dollar")&& box2.equals("Philppine Peso")){
            double us=Double.parseDouble(jTextField1.getText());
            double ph=(double)(us*58.01000);
            jTextField4.setText(String.valueOf(us));
        } else if (box1.equals("US Dollar")&&box2.equals("Euro")) {
            double us=Double.parseDouble(jTextField1.getText());
            double eu=(double)(us*0.96);
            jTextField4.setText(String.valueOf(eu));
        } else if (box1.equals("US Dollar")&&box2.equals("British Pound")){
            double us=Double.parseDouble(jTextField1.getText());
            double bp=(double)(us*0.80);
            jTextField4.setText(String.valueOf(bp));
        } else if (box1.equals("US Dollar")&&box2.equals("Indian Rupee")) {
            double us=Double.parseDouble(jTextField1.getText());
            double ir=(double)(us*87.57);
            jTextField4.setText(String.valueOf(ir));
        } else if (box1.equals("US Dollar")&&box2.equals("Australian Dollar")){
            double us=Double.parseDouble(jTextField1.getText());
            double ad=(double)(us*1.59);
            jTextField4.setText(String.valueOf(ad));
        } else if (box1.equals("US Dollar")&&box2.equals("Canadian Dollar")) {
            double us=Double.parseDouble(jTextField1.getText());
            double cd=(double)(us*1.43);
            jTextField4.setText(String.valueOf(cd));
        } else if (box1.equals("US Dollar")&&box2.equals("Singapore Dollar")){
            double us=Double.parseDouble(jTextField1.getText());
            double sd=(double)(us*1.53);
            jTextField4.setText(String.valueOf(sd));
        } else if (box1.equals("US Dollar")&&box2.equals("Swiss Franc")) {
            double us=Double.parseDouble(jTextField1.getText());
            double sf=(double)(us*0.91);
            jTextField4.setText(String.valueOf(sf));
        } else if (box1.equals("US Dollar")&&box2.equals("Malaysian Ringgit")){
            double us=Double.parseDouble(jTextField1.getText());
            double mr=(double)(us*4.41);
            jTextField4.setText(String.valueOf(mr));
        } else if (box1.equals("US Dollar")&&box2.equals("Japanese Yen")){
            double us=Double.parseDouble(jTextField1.getText());
            double jy=(double)(us*151.73);
            jTextField4.setText(String.valueOf(jy));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
